version: '3.7'

services:

  sample:
    container_name: sample
    image: "phyrion/tfg:latest"
    build:
      context: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 9000:80
    environment:
      - CHOKIDAR_USEPOLLING=true